### ISSUE TITLE
can not find DomError in index file

### ISSUE THREAD

**Issue by bharatAlcovex** [plivo/Plivo-Browser-SDK-v2#144]
Typescript has removed the DOMError type from the latest version and the package is not up to date with it.

I have project setup with typescript 4.7.0.

This issue exists from 4.4.0 onwards.

Please help on that.

**Comment by sanyamjain-plivo** [comment]
@bharatAlcovex Fix merged in the [beta](https://github.com/plivo/Plivo-Browser-SDK-v2/tree/beta) branch.

**Comment by sanyamjain-plivo** [comment]
This is fixed. Closing the issue

**Comment by huynguyen19437** [comment]
I installed the command "npm install plivo-browser-sdk@beta" to get the latest version of plivo-browser-sdk but it's still not working, please help me recheck it @sanyamjain-plivo. Thank you.

**Comment by sanyamjain-plivo** [comment]
@huynguyen19437 The latest version of plivo-browser-sdk is not yet deployed on npm. you can get the latest version from this CDN link:- https://cdn.plivo.com/sdk/browser/v2/plivobeta.min.js

You can add this link as a script tag to your HTML file.

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo
I'm looking forward to hearing from you about the deployment of the latest version of plivo-browser-sdk. Could you deploy it by the end of this month? Thank you very much.

**Comment by TrongNgo** [comment]
@sanyamjain-plivo I have the same issue while starting to apply Plivo to make the outgoing call. 

I'm using Angular 15 with typescript 4.8.4. It is an urgent issue and blocks the team to continue work. I hope the support team public the new package ASAP. Tons of thanks.

**Comment by nhan-truong255** [comment]
It's blocking my team to continue to work. If can, pls public latest version. Thank you.

**Comment by sanyamjain-plivo** [comment]
@huynguyen19437 @nhan-truong255 @TrongNgo The fix is currently in our release pipeline and we are trying our best to release it by mid or late march. As a workaround, you guys can use the CDN mentioned in the comments.

**Comment by TrongNgo** [comment]
Thanks @sanyamjain-plivo, we already apply and it works. But the cdn actually affects the app's first load. We hope to get the next release from your team.

**Comment by huynguyen19437** [comment]
Hi @sanyamjain-plivo, has the latest version of plivo-browser-sdk been deployed on npm? I'm looking forward to hearing from you.

**Comment by sanyamjain-plivo** [comment]
@huynguyen19437 Not yet. We are planning to release it soon

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo when will it be deployed?

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo  when will it be deployed?

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo Hi Sanyamjain, Has the latest version of plivo-browser-sdk been deployed on npm? I'm looking forward to hearing from you.

**Comment by sanyamjain-plivo** [comment]
@huynguyen19437 Hi Huynguyen, We plan to release the fix along with other features that are taking some time but we are working on the release readiness, and once done, we will update the thread.

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo how's the latest version of plivo-browser-sdk going?

**Comment by huynguyen19437** [comment]
@sanyamjain-plivo 
@sanyamjain-plivo how's the latest version of plivo-browser-sdk going?
I'm looking forward to hearing from you.

**Comment by huynguyen19437** [comment]
Hi @sanyamjain-plivo , has the latest version of plivo-browser-sdk been deployed on npm? I'm looking forward to hearing from you.

**Comment by huynguyen19437** [comment]
Hi @sanyamjain-plivo, Has the latest version of plivo-browser-sdk been deployed on npm? I'm looking forward to hearing from you
